### ISSUE TITLE
Finding Papers and Grants from Direct Software Searching

### ISSUE THREAD

**Issue by evamaxfield** [si2-urssi/eager#8]
@rlwhuang This is the issue where we can post ideas about a protocol for software searching:

Off the top of my head I think we should try searching GitHub + GitLab for a few journal title or common doi patterns.

**Comment by nniiicc** [comment]
Let's try to break this down by types of sources first: 

Repository platforms:
- Github 
- Gitlab 

Language Libraries 
- CRAN 
- PyPi 
- NPM 
- crates.io (Rust) 

Domain Repositories:
- ASCL - http://ascl.net/ 
- RopenSci 
- PyOpenSci (not sure if active)

**Comment by rlwhuang** [comment]
I did several searches on these platforms: 
https://docs.google.com/document/d/1Kdue9Luv7VtTSEUFwxkrhzyEXqoOZRwg5RI15mtOyMQ/edit?usp=sharing

**Comment by nniiicc** [comment]
Thanks Richard. A few follow ups:
- I think "National Science Foundation" OR "NSF AWARD" OR "Support" AND "NSF" yields additional relevant results. 
- What information is available that we can or should record from these repositories? Here are some thoughts: 
- - Name (author or PI) 
- - Institution 
- - Link to repository 
- - Software Name 
- - Software Language 
- - Latest Commit (not entirely sure this is necessary) 
- - Award Number (if available)
